### ISSUE TITLE
Out-Barcode doesn't accept content from pipeline

### ISSUE THREAD

**Issue by csdibiase** [gpduck/QrCodes#8]
Content parameter in Out-BarcodeImage.ps1 should accept pipeline input in order to work like other Out-* functions in PowerShell. 

Change line 39 from: 
`[Parameter(Mandatory=$true)]`
to:
`[Parameter(Mandatory=$true,ValueFromPipeline=$true)]`

Not a huge issue and something I was able to fix on my local install, but would certainly be nice to have.

**Comment by gpduck** [comment]
Got support for this added to 1.2.0.80, available on the gallery now.

Thanks for the feedback!
